---
title: "p8105_hw6_zz3039"
output: github_document
date: "2022-11-30"
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)

set.seed(1)
```

## Problem 2

```{r}
homi_data = 
  read_csv("./data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = paste(city, state, sep=", "),
    status = case_when(
      disposition %in% c("Closed by arrest", "Closed without arrest") ~ "solved",
      TRUE ~ "unsolved"),
    status = as.factor(status),
    victim_age = as.numeric(victim_age),
    victim_sex = fct_relevel(victim_sex, "Female")) %>% 
  filter(city_state != "Dallas, TX",
         city_state != "Kansas City, MO",
         city_state != "Phoenix, AZ",
         city_state != "Tulsa, AL",
         victim_race == "White"|victim_race == "Black") %>% 
  select(city_state, everything(), - city, - state) %>% 
  drop_na()
```

obtain the estimate and confidence interval of the adjusted odds ratio for solving homicides comparing male victims to female victims keeping all other variables fixed.

```{r}
bal_data = 
  homi_data %>% 
  filter(city_state == "Baltimore, MD")

fit_bal = 
  glm(status ~ victim_age + victim_sex + victim_race, data = bal_data, family = binomial) 

fit_bal %>% 
  broom::glance()

fit_bal %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>%
  select(term, log_OR = estimate, OR, p.value) %>% 
  knitr::kable(digits = 3)

bal_data %>% 
  modelr::add_predictions(fit_bal) %>% 
  mutate(fitted_prob = boot::inv.logit(pred))
```

